---
version: '3'

tasks:
  provision:
    dir: terraform
    cmds:
      - terraform init
      - terraform apply -auto-approve

  destroy:
    dir: terraform
    cmds:
      - terraform destroy -auto-approve

  configure:
    dir: ansible
    cmds:
      # - yes | ansible all -m ping
      - ansible-playbook playbooks/all.yml

  cleanup:
    deps: [destroy]
    dir: /tmp
    cmds:
      - rm -f *crt *pem *kubeconfig *json

  reset:
    tasks:
      - destroy
      - provision
...
