---
- name: Install necessary packages
  apt:
    pkg:
      - socat
      - conntrack
      - ipset
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Disable swap
  command: swapoff -a
  become: true

- name: Disable swap in fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    line: '# \1'
  become: true

- name: Create necessary directories
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: '0700'
  with_items:
    - /etc/cni
    - /etc/cni/net.d
    - /opt/cni
    - /opt/cni/bin
    - /tmp/containerd
    - /var/lib/kubelet
    - /var/lib/kube-proxy
    - /var/lib/kubernetes
    - /var/run/kubernetes
  become: true

- name: Fetch kube-binaries
  get_url:
    url: "{{ item }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
  with_items:
    - "https://storage.googleapis.com/kubernetes-release/release/{{ kube_ver }}/bin/linux/amd64/kubectl"
    - "https://storage.googleapis.com/kubernetes-release/release/{{ kube_ver }}/bin/linux/amd64/kube-proxy"
    - "https://storage.googleapis.com/kubernetes-release/release/{{ kube_ver }}/bin/linux/amd64/kubelet"
    - "https://github.com/opencontainers/runc/releases/download/v1.0.0-rc93/runc.amd64"
  become: true

- name: Rename runc.amd64 to runc
  copy:
    src: /usr/local/bin/runc.amd64
    dest: /usr/local/bin/runc
    mode: '0755'
    remote_src: true
  become: true

- name: Fetch and unarchive runtime binaries
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    remote_src: true
    extra_opts: [--strip-components=1]
  with_items:
    - {src: "{{ cni_url }}", dest: /opt/cni/bin}
    - {src: "{{ containerd_url }}", dest: /bin}
  become: true

- name: Fetch and unarchive crictl
  unarchive:
    src: "{{ crictl_url }}"
    dest: /usr/local/bin
    owner: root
    group: root
    remote_src: true
    mode: '0755'
  become: true

- name: Copy bridge network configration file
  template:
    src: 10-bridge.conf.j2
    dest: /etc/cni/net.d/10-bridge.conf
    owner: root
    group: root
    mode: '0700'
  become: true

- name: Copy loopback network configuration file
  copy:
    src: 99-loopback.conf
    dest: /etc/cni/net.d/99-loopback.conf
    owner: root
    group: root
    mode: '0700'
  become: true

...
