---
- name: Generate kubeconfig
  shell:
    cmd: >
      kubectl config set-cluster kubernetes-the-hard-way
      --certificate-authority=ca.pem
      --embed-certs=true
      --server=https://{{ loadbalancer_ip }}:6443
      --kubeconfig={{ worker }}.kubeconfig

      kubectl config set-credentials system:node:{{ worker }}
      --client-certificate={{ worker }}.pem
      --client-key={{ worker }}-key.pem
      --embed-certs=true
      --kubeconfig={{ worker }}.kubeconfig

      kubectl config set-context default
      --cluster=kubernetes-the-hard-way
      --user=system:node:{{ worker }}
      --kubeconfig={{ worker }}.kubeconfig

      kubectl config use-context default --kubeconfig={{ worker }}.kubeconfig
    chdir: /tmp
    creates: /tmp/{{ worker }}.kubeconfig
...
