---
- hosts: controller[0]
  tasks:
  # - name: Install pip3
  #   apt:
  #     name: python3-pip
  #     state: present
  #     update_cache: true
  #     cache_valid_time: 3600
  #   become: true

  # - name: Install openshift module for python3
  #   pip:
  #     name: openshift
  #     executable: pip3

  - name: Apply RBAC for kubelet authorization
    k8s:
      state: present
      kubeconfig: "{{ username }}.kubeconfig"
      definition:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          annotations:
            rbac.authorization.kubernetes.io/autoupdate: "true"
          labels:
            kubernetes.io/bootstrapping: rbac-defaults
          name: system:kube-apiserver-to-kubelet
        rules:
          - apiGroups:
              - ""
            resources:
              - nodes/proxy
              - nodes/stats
              - nodes/log
              - nodes/spec
              - nodes/metrics
            verbs:
              - "*"

  - name: Bind system:kube-apiserver-to-kubelet role to kubernetes user
    k8s:
      state: present
      kubeconfig: "{{ username }}.kubeconfig"
      definition:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: system:kube-apiserver
          namespace: ""
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: system:kube-apiserver-to-kubelet
        subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: User
            name: kubernetes
...
